default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ua-books

test:
  <<: *default
  database: ua-books_test

production:
  <<: *default
  database: ua-books
  username: ua-books
  password: <%= ENV['UA-BOOKS_DATABASE_PASSWORD'] %>
