# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ae0482929ae9976345e889b6edbbeffd2f5eb9b8f6d783e8e2e315c4dcdc601a138becb008d28df9ca3fffd83b7e7426d12a038113f207cffb73960bbf052503

test:
  secret_key_base: 3dce071de90b7a677616498276cdd1393ec73ddb4b4f936f27dac14a8543c173d1f822171ca72acae0e819d52c44ddd285ac5c63740ace3fefb61761be74144d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
